<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-26T08:15:32 IST" name="uiCogentoFree CRM" finished-at="2023-05-26T08:15:57 IST" duration-ms="25657">
    <groups>
      <group name="Regression">
        <method signature="LoginPageTest.validateLoginFunctionality()[pri:1, instance:com.TestLayer.LoginPageTest@7c24b813]" name="validateLoginFunctionality" class="com.TestLayer.LoginPageTest"/>
        <method signature="LoginPageTest.validateTitle()[pri:2, instance:com.TestLayer.LoginPageTest@7c24b813]" name="validateTitle" class="com.TestLayer.LoginPageTest"/>
        <method signature="LoginPageTest.validateUrl()[pri:3, instance:com.TestLayer.LoginPageTest@7c24b813]" name="validateUrl" class="com.TestLayer.LoginPageTest"/>
      </group> <!-- Regression -->
      <group name="LoginPage">
        <method signature="LoginPageTest.validateLoginFunctionality()[pri:1, instance:com.TestLayer.LoginPageTest@7c24b813]" name="validateLoginFunctionality" class="com.TestLayer.LoginPageTest"/>
        <method signature="LoginPageTest.validateTitle()[pri:2, instance:com.TestLayer.LoginPageTest@7c24b813]" name="validateTitle" class="com.TestLayer.LoginPageTest"/>
        <method signature="LoginPageTest.validateUrl()[pri:3, instance:com.TestLayer.LoginPageTest@7c24b813]" name="validateUrl" class="com.TestLayer.LoginPageTest"/>
      </group> <!-- LoginPage -->
    </groups>
    <test started-at="2023-05-26T08:15:32 IST" name="Test" finished-at="2023-05-26T08:15:57 IST" duration-ms="25657">
      <class name="com.TestLayer.LoginPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.TestLayer.LoginPageTest@7c24b813]" started-at="2023-05-26T08:15:32 IST" name="setup" finished-at="2023-05-26T08:15:46 IST" duration-ms="13970" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateLoginFunctionality()[pri:1, instance:com.TestLayer.LoginPageTest@7c24b813]" started-at="2023-05-26T08:15:46 IST" name="validateLoginFunctionality" finished-at="2023-05-26T08:15:48 IST" duration-ms="1143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginFunctionality -->
        <test-method signature="validateTitle()[pri:2, instance:com.TestLayer.LoginPageTest@7c24b813]" started-at="2023-05-26T08:15:48 IST" name="validateTitle" finished-at="2023-05-26T08:15:51 IST" duration-ms="3052" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method signature="validateUrl()[pri:3, instance:com.TestLayer.LoginPageTest@7c24b813]" started-at="2023-05-26T08:15:52 IST" name="validateUrl" finished-at="2023-05-26T08:15:52 IST" duration-ms="212" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.TestLayer.LoginPageTest.validateUrl(LoginPageTest.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUrl -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.TestLayer.LoginPageTest@7c24b813]" started-at="2023-05-26T08:15:54 IST" name="teardown" finished-at="2023-05-26T08:15:57 IST" duration-ms="3838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.TestLayer.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- uiCogentoFree CRM -->
</testng-results>
